// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallbacks to prevent crashes
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://opphbdjjkudhrvkutjhn.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wcGhiZGpqa3VkaHJ2a3V0amhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzNjA1NzUsImV4cCI6MjA4NDkzNjU3NX0.ljYXRFWPndFY2J83U_m7WvN2TvDq2J47ZAOAsSwAtJk';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
